name: docs

# Only attempts to build the docs when a PR is made. Publishing is done by docs_update.yml.
on:
  pull_request:
    branches: [main]

jobs:
  docs_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: pip3 install sphinx_rtd_theme
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
