name: pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install requirements
        run: sudo apt install -y python3 python3-pip python3-tk git
      - name: Install python requirements
        run: pip3 install -r requirements.txt
      - name: Run pylint
        run: pylint *.py
